services:

  main-app:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${FASTAPI_PORT}:8000"
    command: "uvicorn --factory src.main:create_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    depends_on:
      - postgres
    volumes: 
      - ..:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge