services: 
  rabbitmq: 
    image: "heidiks/rabbitmq-delayed-message-exchange:latest" 
    hostname: rabbitmq
    restart: always 
    ports: 
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - ./rabbitmq_data2:/var/lib/rabbitmq
    env_file:
      - ../.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766

    networks:
      - backend

  consumer:
    build: 
      context: ..
      dockerfile: Dockerfile
    container_name: consumer
    env_file:
      - ../.env
    depends_on:
      - rabbitmq
    command: sh -c "sleep 10 && python -m src.infrastructure.broker_messages.rabbitmq.consumer"
    networks:
      - backend


networks:
  backend:
    driver: bridge